name: 收到访客 Ping

on:
  repository_dispatch:
    types: [ping]

jobs:
  mail:
    runs-on: ubuntu-latest
    steps:
      - name: 发邮件
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          secure: true
          username: 1828339242@qq.com
          password: trdlxempxmpmejfb
          subject: "新访客 IP 定位"
          to: 1828339242@qq.com
          from: GitHub Pages 机器人
          html_body: |
            <p>时间：${{ github.event.repository.updated_at}}</p>
            <p>IP：${{ github.event.client_payload.ip }}</p>
            <p>坐标：${{ github.event.client_payload.latitude }}, ${{ github.event.client_payload.longitude }}</p>
            <p>位置：${{ github.event.client_payload.country_name }} ${{ github.event.client_payload.region }} ${{ github.event.client_payload.city }}</p>